name: TODO CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: ./todoBackend
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./todo
        run: npm install

      - name: Build React app
        working-directory: ./todo
        run: npm run build